<?php

namespace App\DTOs\Supplier;

class SupplierCreateDTO
{
    public function __construct(
        public readonly string $name,
        public readonly string $email,
        public readonly ?string $phoneNumber = null,
        public readonly ?string $description = null,
        public readonly ?string $address = null,
        public readonly ?string $website = null,
        public readonly ?string $logoUrl = null,
    ) {}

    /**
     * Column => value, ready for the model. The slug is generated by the service.
     */
    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'email' => $this->email,
            'phone_number' => $this->phoneNumber,
            'description' => $this->description,
            'address' => $this->address,
            'website' => $this->website,
            'logo_url' => $this->logoUrl,
        ];
    }
}
